language: php

php:
  - 7.0

before_script:
  - chmod 777 -R storage
  - cp .env.travis .env
  - mysql -e 'create database laravel;'
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit

sudo: required
dist: trusty

addons:
   chrome: stable

install:
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
   - php artisan dusk